---
abstract: 'stats ID list'
author:
  - 'Dai Okabayashi <bayashi@cpan.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Statistics-UIDList
provides:
  Statistics::UIDList:
    file: lib/Statistics/UIDList.pm
    version: 0.01
requires:
  Carp: 0
  perl: 5.008001
resources:
  bugtracker: http://github.com/bayashi/Statistics-UIDList/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/bayashi/Statistics-UIDList
version: 0.01
